plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.2'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.ccommit'
version = '0.0.1-SNAPSHOT'
description = 'monolith-to-msa for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Web
	implementation 'org.springframework.boot:spring-boot-starter-web'
	
	// Actuator (Health Check)
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	
	// Validation
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	
	// JPA
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	
	// Retry
	implementation 'org.springframework.retry:spring-retry:2.0.5'
	implementation 'org.springframework:spring-aspects'
	
	// Database
	implementation 'com.h2database:h2'
	runtimeOnly 'com.mysql:mysql-connector-j'
	
	// Redis Cache
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-cache'
	
	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	
	// Dev Tools
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	
	// Test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

// Retry 활성화
tasks.named('compileJava') {
	options.annotationProcessorPath = configurations.annotationProcessor
}
